version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 8889
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  database:
    image: mysql:8.0.26
    platform: linux/amd64
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "8890:8890"
